#!/usr/bin/env bash
# Shared settings for the deployment scripts. Override any of these from the
# environment, e.g. THUNDERID_VERSION=1.0.2 ./fetch-thunderid.sh

THUNDERID_VERSION="${THUNDERID_VERSION:-1.0.1}"
THUNDERID_PORT="${THUNDERID_PORT:-8090}"
THUNDERID_ADMIN_USERNAME="${THUNDERID_ADMIN_USERNAME:-admin}"

# ThunderID bootstraps with whatever admin password it is given; there is no
# built-in default (it generates a random one if unset). These are fine for a
# local demo and nowhere else.
THUNDERID_ADMIN_PASSWORD="${THUNDERID_ADMIN_PASSWORD:-Admin@123}"

# Gates ThunderID's Direct API endpoints. Generated by setup.sh when unset; set
# explicitly here so the value is known to the scripts that need to call them.
THUNDERID_DIRECT_AUTH_SECRET="${THUNDERID_DIRECT_AUTH_SECRET:-trustgate-local-direct-secret}"

TRUSTGATE_PORT="${TRUSTGATE_PORT:-8000}"

DEPLOYMENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$DEPLOYMENT_DIR/.." && pwd)"
# Downloads land here and are gitignored -- the distribution is ~34MB.
DIST_DIR="$DEPLOYMENT_DIR/dist"
RUN_DIR="$DEPLOYMENT_DIR/run"

detect_platform() {
  local os arch
  case "$(uname -s)" in
    Darwin) os="macos" ;;
    Linux) os="linux" ;;
    *)
      echo "unsupported OS: $(uname -s) -- ThunderID ships macos, linux and win builds" >&2
      return 1
      ;;
  esac
  case "$(uname -m)" in
    arm64 | aarch64) arch="arm64" ;;
    x86_64 | amd64) arch="x64" ;;
    *)
      echo "unsupported architecture: $(uname -m)" >&2
      return 1
      ;;
  esac
  echo "${os}-${arch}"
}

THUNDERID_PLATFORM="${THUNDERID_PLATFORM:-$(detect_platform)}"
THUNDERID_DIST_NAME="thunderid-${THUNDERID_VERSION}-${THUNDERID_PLATFORM}"
THUNDERID_ZIP="${THUNDERID_DIST_NAME}.zip"
THUNDERID_URL="https://github.com/thunder-id/thunderid/releases/download/v${THUNDERID_VERSION}/${THUNDERID_ZIP}"
THUNDERID_HOME="$DIST_DIR/$THUNDERID_DIST_NAME"
THUNDERID_BASE_URL="https://localhost:${THUNDERID_PORT}"
